@startuml Диаграмма состояний(Application)
title Диаграмма состояний(Application)
scale 2
[*] --> CREATED: Заявка прошла\nвалидацию 
CREATED --> PENDING: Заявка отправленна в KYC
PENDING --> APPROVED: Заявка прошла\nпроверку успешно
PENDING --> REJECTED: Заявка не прошла\nпроверку KYC
PENDING --> MANUAL_REVIEW: Заявка передана на\nручное рассмотрение
APPROVED --> COMPLETED: Core Banking подтвердил\nсоздание счёта
MANUAL_REVIEW --> COMPLETED: Заявка прошла\nручную проверку успешно
MANUAL_REVIEW --> REJECTED: Заявка не прошла\nручную проверку
COMPLETED --> [*]
REJECTED --> [*]
@enduml